name: Auto-fix lint and format

on:
  schedule:
    - cron: '0 3 * * 1' # weekly (UTC)
  workflow_dispatch:

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run ESLint fixes
        run: npx eslint "src/**/*.{js,jsx,ts,tsx}" --fix || true

      - name: Run Prettier fixes
        run: npx prettier --write "src/**/*.{js,jsx,ts,tsx,json,css,md}"

      - name: Create PR if there are changes
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: chore(autofix): apply ESLint and Prettier fixes
          branch: autofix/eslint-prettier
          title: "Auto-fix: ESLint & Prettier fixes"
          body: |
            This PR contains automatic fixes applied by the Auto-fix workflow (ESLint --fix and Prettier).
            Please review and merge if the changes are acceptable.
          labels: autofix,automation
